config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  get 'relations/create'

  get 'relations/destroy'

  root to: 'users#new'

  get "logout" => "logins#destroy", :as => "logout"
  get "login" => "logins#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :logins, only: [:new, :create, :destroy]
  resources :myposts, only: [:create, :destroy]
  resources :relations, only: [:create, :destroy]

end

app/models/mypost.rb
class Mypost < ActiveRecord::Base

  mount_uploader :photo, PhotoUploader

  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 1000 }

  default_scope -> { order('created_at DESC') }

  def self.followed_by(user)
    joins('INNER JOIN relations ON myposts.user_id=relations.followed_id').where('relations.follower_id=:user_id OR myposts.user_id=:user_id', user_id: user.id).uniq
  end
end

app/models/relation.rb
class Relation < ActiveRecord::Base

  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  mount_uploader :photo, PhotoUploader

  has_many :myposts, dependent: :destroy

  has_many :relations, foreign_key: 'follower_id', dependent: :destroy
  has_many :followed_users, through: :relations, source: :followed
  has_many :reverse_relations, foreign_key: 'followed_id', class_name: 'Relation', dependent: :destroy
  has_many :followers, through: :reverse_relations, source: :follower

  validates :password, length: { minimum: 5 }, :on => :create
  validates :password, confirmation: true
  validates :email, uniqueness: true, email_format: { message: 'has invalid format' }

  def following?(user)
    relations.find_by(followed_id: user.id)
  end

  def follow!(user) #подписаться на юзера
    relations.create!(followed_id: user.id)
  end

  def unfollow!(user) #отписаться от юзера
    relations.find_by(followed_id: user.id).destroy!
  end

  def news_feed
    Mypost.followed_by(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_admin_user!
    redirect_to root_url unless current_user.try(:admin?)
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
    if @user = login(params[:email], params[:password], params[:remember_me])
      redirect_back_or_to(user_path(@user), notice: 'Ваша персональная страница!')
    else
      flash.now[:alert] = 'Войти не удалось'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => 'Ждём Вас снова!'
  end
end

app/controllers/myposts_controller.rb
class MypostsController < ApplicationController
  before_action :require_login

  def create
    @mypost = current_user.myposts.new(mypost_params)
    if @mypost.save
      PostMailer.new_mypost(@mypost).deliver_later
      redirect_back_or_to(user_path(current_user), notice: 'Новая запись добавлена!')
    else
      flash[:alert] = 'Нет содержания!'
      redirect_to user_path(current_user)
    end
  end

  def destroy
    if @mypost = current_user.myposts.find_by(id: params[:id])
       @mypost.destroy
    end
    redirect_to user_path(current_user)
  end

  private

  def mypost_params
    params.require(:mypost).permit(:content, :photo)
  end
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  before_action :require_login

  def create
    @user = User.find(params[:relation][:followed_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Relation.find(params[:id]).followed
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]
  before_action :current,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  before_action :find_user, only: [:show, :edit, :update, :destroy, :following, :followers]

  def index
    @users = User.page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => 'Благодарим за регистрацию!'
    else
      render :new
    end
  end

  def show
    @myposts = @user.news_feed.page(params[:page]).per(5)
    @mypost = @user.myposts.new
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
        if @user == current_user
          flash[:notice] = 'Себя нельзя удалить!'
          redirect_to users_url
        else
          @user.destroy
          flash[:success] = 'User deleted.'
          redirect_to users_url
        end
  end

  def following
    @title = 'Following'
    @users = @user.followed_users.page(params[:page]).per(5)
    render 'show_follow'
  end

  def followers
    @title = 'Followers'
    @users = @user.followers.page(params[:page]).per(5)
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:username,:email, :password, :password_confirmation, :photo)
  end

  def find_user
    @user = User.find(params[:id])
  end

  def current
    @user = User.find(params[:id])
    redirect_to(root_url) if @user != current_user
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user?(user)
    user == current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Atmos8</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" if Rails.env.production? %>
  <!-- Optional theme -->
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css" if Rails.env.production? %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js" if Rails.env.production? %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="navbar">
    <ul class="nav navbar-nav" >
      <% unless current_user %>
        <li><%= link_to "Sign up", signup_path %></li>
        <li><%= link_to "log in", login_path %></li>
      <% end %>
    </ul>
    <br>
    <% if current_user %>
      <ul class="nav navbar-nav pull-right">
        <li><span>Приветствуем Вас, <%= current_user.username %>.</span></li>
        <% if current_user.admin %>
          <li><%= link_to 'Admin Panel', admin_dashboard_path %></li>
        <% end %>
        <li><%= link_to 'My Profile', user_path(current_user) %>
        <li><%= link_to 'Edit', edit_user_path(current_user) %></li>
        <li><%= link_to 'Users', users_path %></li>
        <li><%= link_to 'Log Out', logout_path %></li>
      </ul>
    <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/logins/new.html.slim
h1 Вход в систему
p
  =flash.now[:alert]
= form_tag logins_path do
  .form-group
    = label_tag :email
    = email_field_tag :email, params[:email], class: 'form-control'
  .form-group
    = label_tag :password
    = password_field_tag :password, nil, class: 'form-control'
  .form-group
    = label_tag :remember_me
    = check_box_tag :remember_me

  = submit_tag 'Войти', class: 'btn btn-default'

app/views/myposts/_mypost.html.slim
li
  span = image_tag mypost.user.photo_url(:mini)
  span = link_to mypost.user.username, mypost.user
  span class='content' = mypost.content
  - if mypost.photo_url.to_s != "/no_image.png"
    div = image_tag(mypost.photo_url.to_s)
  span class='timestamp'
    = time_ago_in_words(mypost.created_at)
    = social_share_button_tag("My Home Page", :url => "http://atmos8.com")
  - if current_user?(mypost.user)
    div = link_to 'delete', mypost, method: :delete, data: { confirm: "You sure?" }

app/views/myposts/_mypost_form.html.slim
= simple_form_for @mypost, html: { multipart: true } do |f|
  = f.input :content
  = f.input :photo
  = f.button :submit, 'Сохранить'

app/views/users/_follow.html.slim
= simple_form_for(current_user.relations.new(followed_id: @user.id)) do |f|
  div
    = f.input :followed_id, as: :hidden
  = f.submit 'Добавить в друзья', class: 'btn btn-large btn-primary'

app/views/users/_form.html.slim
= simple_form_for @user, html: { multipart: true } do |f|
  - if @user.errors.any?
    .error_messages
      h2 Form is invalid
      ul
        - for message in @user.errors.full_messages
          li
            = message
  = f.input :username
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  = f.input :photo
  = f.button :submit, 'Сохранить'

app/views/users/_unfollow.html.slim
= simple_form_for(current_user.relations.find_by(followed_id: @user), html: { method: :delete }) do |f|
  = f.submit 'Удалить из друзей', class: 'btn btn-large'

app/views/users/_users_list.html.slim
ul class='users'
  - @users.each do |user|
    li
      = image_tag user.photo_url(:thumb)
      = link_to user.username, user
    - if current_user.admin? && !current_user?(user)
      = link_to "delete", user, method: :delete, data: { confirm: "You sure?" }
    li
      = user.email
    br
= paginate @users

app/views/users/edit.html.slim
p
  =flash.now[:notice]

h1 Update your profile

= render :partial => 'form'

app/views/users/index.html.slim
p
  =flash.now[:notice]
  =flash.now[:success]
h1 All users
= render partial: 'users_list'

app/views/users/new.html.slim
p
  =flash.now[:notice]

h1 Форма регистрации

= render :partial => 'form'

app/views/users/show.html.slim
p
  =flash.now[:alert]
  =flash.now[:notice]
h1 Show your profile

aside
  ul
    li = image_tag(@user.photo_url.to_s)
    li 
      = @user.username
    li 
      = @user.email
    li
      = link_to(following_user_path(@user))
        strong.statistic
          = "Друзья: "
          = @user.followed_users.count
    li
      = link_to(followers_user_path(@user))
        strong.statistic 
          = 'Подписчики: '
          = @user.followers.count
    - unless current_user?(@user)
      - if current_user.following?(@user)
        li
          = render 'unfollow'
      - else
        li
          = render 'follow'

  - if current_user
    - if @user.id == current_user.id
      = link_to 'Редактировать', edit_user_path, class: 'btn btn-danger'
      = render '/myposts/mypost_form'

- if @user.myposts.any?
  h3 My posts
  
  ol class='myposts'
    = render @myposts
  = paginate @myposts

app/views/users/show_follow.html.slim
h1 = @title

= render partial: 'users_list'